[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.optimizer]
enabled = true
runs = 200

[rpc_endpoints]
base = "https://base-rpc.publicnode.com"
base_sepolia = "https://sepolia.base.org"
localhost = "http://127.0.0.1:8545"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
